simpleBean3:
  name: "justABean3"
myConfig:
  Bean4:
    name: "just a name"

logging:
  level:
    root: "DEBUG"

spring:
  profiles:
    #active: "lecture"
    active: "default"
  #main:
    #banner-mode: "off"